### ISSUE TITLE
Running experiments using RSPMNs

### ISSUE THREAD

**Issue by yannickl96** [c0derzer0/RSPMN#1]
Hello,

I am interested in running the experiments from your paper "Recurrent Sum-Product-Max Networks for Decision Making in Perfectly-Observed Environments". I tried to follow your README in this repository and managed to train an RSPMN.
However, I struggle to plot the networks as described in the README. Maybe you can help me out here.
I get the following error message:
```
Traceback (most recent call last):
  File "example.py", line 47, in <module>
    plot_spn(spmn_structure_two_time_steps, "./two_steps.pdf", feature_labels=["State", "Action", "Reward"])
  File "/home/yannick/miniconda3/envs/rspmn/lib/python3.7/site-packages/spflow-0.0.34-py3.7.egg/spn/io/Graphics.py", line 96, in plot_spn
    g, labels = get_networkx_obj(spn, feature_labels)
  File "/home/yannick/miniconda3/envs/rspmn/lib/python3.7/site-packages/spflow-0.0.34-py3.7.egg/spn/io/Graphics.py", line 63, in get_networkx_obj
    label = feature_labels[n.scope[0]] 
IndexError: list index out of range
```
You can find the code below:
```
import pandas as pd
import numpy as np

csv_path = "FrozenLake/FrozenLake.csv"
df = pd.read_csv(csv_path, sep=',')
train_data = df.values
partial_order = [["state"],["action"],["reward"]]
decision_nodes = ["action"]
utility_nodes = ["reward"]
feature_names = [var for var_set in partial_order for var in var_set]
batch_size = 512
sequence_split = 5
num_vars = 3
from spn.structure.StatisticalTypes import MetaType
# Utility variable is the last variable. Other variables are of discrete type
meta_types = [MetaType.DISCRETE]*2+[MetaType.UTILITY]

from spn.algorithms.RSPMNnewAlgo import RSPMNnewAlgo
rspmn = RSPMNnewAlgo(partial_order, decision_nodes, utility_nodes, feature_names,
                     meta_types, cluster_by_curr_information_set=True,
                     util_to_bin=False)
wrapped_two_timestep_data = rspmn.InitialTemplate.wrap_sequence_into_two_time_steps(train_data)
spmn_structure_two_time_steps, top_network, initial_template_network = rspmn.InitialTemplate.build_initial_template(wrapped_two_timestep_data)

template = rspmn.InitialTemplate.template_network
# Learn final template using sequential data
template = rspmn.hard_em(train_data, template, False)
# if numpy array cannot hold whole of train_data,
# updates can be made on batches of data and/or by splliting sequence as follows
for i in range(0, len(train_data), batch_size):
    for j in range(0, 8, sequence_split):
        template = rspmn.hard_em(train_data[i:i+batch_size, j*num_vars:(j+sequence_split)*num_vars], template, False)

rspmn.update_weights(rspmn.template)

meu_list, lls_list = rspmn.value_iteration(template, 300)

# to select an action in state 0
test_data = [0, np.nan, np.nan]
test_data = np.array(test_data).reshape(1, len(test_data))
# rspmn.select_actions returns a numpy array of data filled with best decision values at corresponding decision variables
# and most probable explaination (MPE) values for leaf variables
data = rspmn.select_actions(rspmn.template, test_data, meu_list, lls_list)
# data is represented as [state, action, utility]

from spn.io.Graphics import plot_spn
plot_spn(spmn_structure_two_time_steps, "./two_steps.pdf", feature_labels=["State", "Action", "Reward"])
plot_spn(top_network, "./top_network.pdf", feature_labels=["State", "Action", "Reward"])
plot_spn(initial_template_network, "./template_network.pdf", feature_labels=["State", "Action", "Reward"])

# to obtain the Maximum Expected Utility of state 0
test_data = [0, np.nan, np.nan]
test_data = np.array(test_data).reshape(1, len(test_data))
meu = rspmn.meu_of_state(rspmn.template, test_data, meu_list, lls_list)[0]
print(meu)
```
Maybe you can give me a pointer where I might be doing something wrong.

Best regards,
Yannick

**Comment by c0derzer0** [comment]
Hello Yannick,

Thanks for reaching out to me. The error is due to the feature labels
argument which is given as

feature_labels=["State", "Action", "Reward"].

The spmn_structure_two_time_steps has 6 variables ["State", "Action",
"Reward"] for two time steps. Modify it as follows

feature_labels=["State0", "Action0", "Reward0", "State1", "Action1", "Reward1"].

I think that should fix the issue. Also, for learning the template,
you can use any one of the following ways,

# Learn final template using sequential data
template = rspmn.hard_em(train_data, template, False)

or

# if numpy array cannot hold whole of train_data,
# updates can be made on batches of data and/or by splliting sequence as follows
for i in range(0, len(train_data), batch_size):
    for j in range(0, 8, sequence_split):
        template = rspmn.hard_em(train_data[i:i+batch_size,
j*num_vars:(j+sequence_split)*num_vars], template, False)

Try to learn the model just with the following code for this dataset.
template = rspmn.hard_em(train_data, template, False)

and update the template using
rspmn.update_weights(rspmn.template)

Best,

Hari Teja Tatavarti

**Comment by yannickl96** [comment]
Hello Hari,

thank you for your quick reply! Plotting the SPNs worked now, but I am still a little bit confused about the last bit when printing the MEU: According to the README I would expect a scalar. However, what I get is a list of numpy arrays (code as above with your suggested changes). I would be happy if you could clear up my confusion a little bit.

Best,
Yannick

**Comment by yannickl96** [comment]
I have to correct my above statement, I forgot to add the indexing after the [0] of the method return value. My code looks as follows:
```
import pandas as pd
import numpy as np

csv_path = "FrozenLake/FrozenLake.csv"
df = pd.read_csv(csv_path, sep=',')
train_data = df.values
partial_order = [["state"],["action"],["reward"]]
decision_nodes = ["action"]
utility_nodes = ["reward"]
feature_names = [var for var_set in partial_order for var in var_set]
batch_size = 512
sequence_split = 5
num_vars = 3
from spn.structure.StatisticalTypes import MetaType
# Utility variable is the last variable. Other variables are of discrete type
meta_types = [MetaType.DISCRETE]*2+[MetaType.UTILITY]

from spn.algorithms.RSPMNnewAlgo import RSPMNnewAlgo
rspmn = RSPMNnewAlgo(partial_order, decision_nodes, utility_nodes, feature_names,
                     meta_types, cluster_by_curr_information_set=True,
                     util_to_bin=False)
wrapped_two_timestep_data = rspmn.InitialTemplate.wrap_sequence_into_two_time_steps(train_data)
spmn_structure_two_time_steps, top_network, initial_template_network = rspmn.InitialTemplate.build_initial_template(wrapped_two_timestep_data)

template = rspmn.InitialTemplate.template_network
# Learn final template using sequential data
template = rspmn.hard_em(train_data, template, False)
# if numpy array cannot hold whole of train_data,
# updates can be made on batches of data and/or by splliting sequence as follows
#for i in range(0, len(train_data), batch_size):
#    for j in range(0, 8, sequence_split):
#
#        template = rspmn.hard_em(train_data[i:i+batch_size, j*num_vars:(j+sequence_split)*num_vars], template, False)

template = rspmn.hard_em(train_data, template, False)
rspmn.update_weights(rspmn.template)

meu_list, lls_list = rspmn.value_iteration(template, 300)

# to select an action in state 0
test_data = [0, np.nan, np.nan]
test_data = np.array(test_data).reshape(1, len(test_data))
# rspmn.select_actions returns a numpy array of data filled with best decision values at corresponding decision variables
# and most probable explaination (MPE) values for leaf variables
data = rspmn.select_actions(rspmn.template, test_data, meu_list, lls_list)
# data is represented as [state, action, utility]

from spn.io.Graphics import plot_spn
plot_spn(spmn_structure_two_time_steps, "./two_steps.pdf", feature_labels=["State0", "Action0", "Reward0", "State1", "Action1", "Reward1"])
plot_spn(top_network, "./top_network.pdf", feature_labels=["State", "Action", "Reward"])
plot_spn(initial_template_network, "./template_network.pdf", feature_labels=["State", "Action", "Reward"])

# to obtain the Maximum Expected Utility of state 0
test_data = [0, np.nan, np.nan]
test_data = np.array(test_data).reshape(1, len(test_data))
meu = rspmn.meu_of_state(rspmn.template, test_data, meu_list, lls_list)[0][:,0]
print("MEU = ", meu)
```
However, I get a TypeError:
```
    meu = rspmn.meu_of_state(rspmn.template, test_data, meu_list, lls_list)[0][:,0]
TypeError: list indices must be integers or slices, not tuple
```
I would appreciate if you helped me out here :)

Best,
Yannick

**Comment by c0derzer0** [comment]
Hi Yannock,

meu = rspmn.meu_of_state(rspmn.template, test_data, meu_list, lls_list)[0] should be a numpy array with MEU values at each node and the first value would be the MEU at the root which is desired in this case. From your previous comment it is correctly returning a numpy array. I am not sure why the indexing is not working on the numpy array though. For some reason it is returning a list I believe. Can you print the meu and its type and check? It would help if you can post the output you are getting in meu.
